apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: {{ .Values.service.name }}
  name: {{ .Values.service.name }}
spec:
  ports:
  - name: headless
    port: 55555
    targetPort: 0
  selector:
    service: {{ .Values.service.name }}
status:
  loadBalancer: {}
